In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. NumPy Array

In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

In [ ]:
a[0]

In [ ]:
a[2:5]

In [ ]:
a[:6]

In [ ]:
a[3:]

In [ ]:
a[-1]

In [ ]:
a[-5:]

In [ ]:
a[-5:-1]

In [ ]:
np.size(a)

In [ ]:
np.shape(a)

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

In [ ]:
a[0,0]

In [ ]:
a[1,:]

In [ ]:
a[:,-1]

In [ ]:
a[:,-1] = 0
a

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

In [ ]:
np.size(a,1)

In [ ]:
np.ndim(a)

## Data is Matrix.

In [ ]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

In [ ]:
np.array(np_mix_matrix[:,1], dtype = int)

# 2. Special Type of Matrix

In [ ]:
a = np.zeros((2,2))
a

In [ ]:
b = np.ones((2,2))
b

In [ ]:
c = np.full((2,2),8)
c

In [ ]:
d = np.eye(2)
d

In [ ]:
c*d

In [ ]:
2*np.ones((2,2))

In [ ]:
np.sqrt(np.full((2,2),4))

In [ ]:
np.empty([5,5])

# 3. Random

In [2]:
np.random.rand()

0.9121151943768038

In [3]:
np.random.randint(5)

3

In [4]:
np.seed = 1
np.random.randint(2,5)

4

In [5]:
#Ex.1
np.round(np.random.rand(5,5)*1000)

array([[508., 883., 341.,  48., 879.],
       [ 74., 412.,  15., 717., 588.],
       [855., 568., 826., 253., 751.],
       [650., 508., 921.,  30., 592.],
       [496., 350., 924., 654., 618.]])

In [6]:
np.random.rand(5,5)

array([[0.65934927, 0.93229532, 0.08386502, 0.3341655 , 0.54302444],
       [0.74941119, 0.54236516, 0.51911908, 0.13937368, 0.04053625],
       [0.95756751, 0.56804939, 0.57605195, 0.80090962, 0.01929688],
       [0.97216148, 0.89535811, 0.79753226, 0.46742685, 0.66721303],
       [0.4683996 , 0.10464632, 0.93259902, 0.26606915, 0.23358144]])

In [7]:
np.round(np.random.rand(5,5))

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 1., 1.],
       [0., 1., 0., 1., 1.],
       [1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [8]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

array([9, 5, 2, 8, 9])

In [9]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5, replace = False)

array([4, 3, 8, 2, 9])

In [10]:
np_matrix = np.random.rand(5,5)
idx_choose = np.random.choice(5,3)
np_matrix_choose = np_matrix[idx_choose,:]
np_matrix_choose

array([[0.55626538, 0.24780258, 0.48135431, 0.01741306, 0.78860506],
       [0.06030298, 0.29851311, 0.34636782, 0.07851583, 0.92769206],
       [0.55626538, 0.24780258, 0.48135431, 0.01741306, 0.78860506]])

In [48]:
#Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.
np_mt=np.random.rand(10,5)
x_ch=np.round(np_mt[:,4])
np_mt[:,4]=x_ch
np_mt

array([[0.97241527, 0.81759738, 0.51781594, 0.21600718, 0.        ],
       [0.21804635, 0.08198804, 0.84700605, 0.10510532, 1.        ],
       [0.83761031, 0.30286139, 0.95391744, 0.42930301, 0.        ],
       [0.438737  , 0.19476926, 0.39404558, 0.49735036, 1.        ],
       [0.69280963, 0.40794979, 0.43083496, 0.87325682, 0.        ],
       [0.74800345, 0.78654715, 0.12862438, 0.03154655, 0.        ],
       [0.05107957, 0.31101132, 0.63012253, 0.41657096, 0.        ],
       [0.22915754, 0.53708001, 0.7597624 , 0.64344337, 0.        ],
       [0.31603881, 0.16699336, 0.86688183, 0.04017953, 0.        ],
       [0.80408338, 0.66954047, 0.11884444, 0.62116163, 0.        ]])

In [46]:
np_matrix = np.random.randint(11,size = (5,5))
np_matrix

array([[ 1,  1,  0,  1, 10],
       [ 5, 10,  3,  8,  5],
       [ 5,  3,  1,  8,  3],
       [ 1,  9,  0,  1,  7],
       [ 0,  6,  4,  5,  1]])

In [12]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[2, 0, 2, 1, 0],
       [0, 0, 1, 1, 1],
       [2, 0, 1, 2, 0],
       [2, 1, 1, 2, 2],
       [0, 2, 1, 0, 0]])

In [13]:
i,j = np.where(np_matrix == 2)

In [14]:
i

array([0, 0, 2, 2, 3, 3, 3, 4])

In [15]:
j

array([0, 2, 0, 3, 0, 3, 4, 1])

In [76]:
#Ex 3. Why we cannot use this index ? Please fix it !!
np_matrix = np.random.randint(3,size = (6,5))
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[0, 0, 0, 2, 1],
       [0, 0, 1, 1, 0],
       [2, 1, 0, 1, 1],
       [0, 2, 1, 1, 0],
       [0, 0, 0, 2, 1]])

In [57]:
np_matrix = np.delete(np_matrix,[1,2],0)
np_matrix

array([[1, 2, 0, 0, 0],
       [1, 2, 0, 1, 1],
       [2, 1, 1, 0, 1],
       [0, 0, 2, 2, 1]])

In [71]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[4, 7, 2, 3, 3],
       [8, 6, 2, 7, 4],
       [7, 6, 0, 8, 6],
       [2, 2, 8, 9, 7],
       [7, 3, 9, 9, 9]])

In [19]:
result = (np_matrix == 2)
result

array([[False, False,  True, False, False],
       [False, False, False, False,  True],
       [False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False,  True, False]])

In [20]:
np_matrix[result] = 99
np_matrix

array([[ 9,  1, 99,  4,  4],
       [ 4,  5,  0,  1, 99],
       [ 4,  0,  8,  9,  3],
       [ 7, 99,  4,  9,  7],
       [ 6,  0,  5, 99,  5]])

In [ ]:
# Ex 4. Randomly create a data matrix of 10 samples with 5 features. 
# Then, randomly create a label vector for 10 samples. 
# Finally, seperate samples into 2 groups
# Group 1 called train_data (label == 0)
# Group 2 called test_data (label == 1)

In [80]:
#4.1 data matrix
data_mt=np.random.randint(10,size=(10,5))
data_mt

array([[5, 7, 7, 1, 3],
       [3, 6, 1, 5, 7],
       [2, 8, 2, 8, 4],
       [9, 0, 3, 7, 1],
       [5, 1, 2, 3, 3],
       [2, 3, 7, 6, 5],
       [1, 4, 3, 2, 2],
       [4, 6, 2, 5, 1],
       [3, 4, 9, 0, 2],
       [8, 1, 1, 8, 2]])

In [100]:
#4.2 label vector
lv=np.random.randint(2,size=10)
lv

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1])

In [101]:
#4.3 train data
#tr_data=(lv==0)
#data_mt[tr_data]
data_mt[lv==0]

array([[5, 7, 7, 1, 3],
       [3, 6, 1, 5, 7],
       [2, 8, 2, 8, 4],
       [2, 3, 7, 6, 5],
       [1, 4, 3, 2, 2]])

In [102]:
#4.4 test data
#te_data=(lv==0)
#data_mt[te_data]
data_mt[lv==1]

array([[9, 0, 3, 7, 1],
       [5, 1, 2, 3, 3],
       [4, 6, 2, 5, 1],
       [3, 4, 9, 0, 2],
       [8, 1, 1, 8, 2]])

In [103]:
data = np.random.randint(5,size=(5,5)) + 1
data

array([[3, 4, 4, 2, 5],
       [5, 3, 5, 1, 2],
       [4, 5, 4, 4, 5],
       [3, 3, 4, 1, 5],
       [2, 5, 2, 2, 3]])

# 4. Important Function

In [22]:
np.max(data)

5

In [23]:
np.max(data,0)

array([5, 5, 5, 4, 5])

In [24]:
np.max(data,1)

array([5, 5, 5, 5, 5])

In [25]:
np.sum(data)

74

In [26]:
np.average(data)

2.96

In [27]:
data[0,:]

array([2, 3, 3, 3, 5])

In [28]:
np.argmax(data[0,:])

4

In [29]:
np.argmin(data[0,:])

0

In [30]:
np.sort(data[0,:])

array([2, 3, 3, 3, 5])

In [31]:
np.argsort(data[0,:])

array([0, 1, 2, 3, 4])

In [104]:
#Ex.5 How to sort in decreasing order using np.sort
np.sort(data[0,:])[::-1]

array([5, 4, 4, 3, 2])

In [32]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [33]:
np.linspace(5,10,10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [34]:
data = np.round(np.random.random((5,5))*3)
data

array([[1., 2., 3., 2., 2.],
       [3., 2., 3., 3., 3.],
       [2., 1., 1., 2., 1.],
       [1., 3., 1., 1., 2.],
       [2., 2., 2., 3., 1.]])

In [35]:
data.shape

(5, 5)

In [36]:
data.reshape(1,25)

array([[1., 2., 3., 2., 2., 3., 2., 3., 3., 3., 2., 1., 1., 2., 1., 1.,
        3., 1., 1., 2., 2., 2., 2., 3., 1.]])

In [37]:
tile = [[1,2],
        [3,4]]
tile

[[1, 2], [3, 4]]

In [38]:
np.tile(tile,(4,1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [105]:
#Ex. 6 Extract all the numbers divisible by 3 from np_test. Note: Please use only 1 line command
np_test= np.arange(25).reshape(5,5)
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [106]:
#6
np_test[(np.arange(25).reshape(5,5))%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [107]:
# Ex.7 Change diagonal element of np_test to 0. Note: Please use only 1 line command (Google it!!)
#
np_test

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [133]:
#7
np_test[np.fill_diagonal(np_test,0)]

array([[[ 0,  1,  2,  3,  4],
        [ 5,  0,  7,  8,  9],
        [10, 11,  0, 13, 14],
        [15, 16, 17,  0, 19],
        [20, 21, 22, 23,  0]]])

# diagonal
https://numpy.org/doc/stable/reference/generated/numpy.fill_diagonal.html