In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# 1. NumPy Array

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
a[0]

1

In [5]:
a[2:5]

array([3, 4, 5])

In [6]:
a[:6]

array([1, 2, 3, 4, 5, 6])

In [7]:
a[3:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [8]:
a[-1]

10

In [9]:
a[-5:]

array([ 6,  7,  8,  9, 10])

In [10]:
a[-5:-1]

array([6, 7, 8, 9])

In [11]:
np.size(a)

10

In [12]:
np.shape(a)

(10,)

In [13]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
a[0,0]

1

In [15]:
a[1,:]

array([4, 5, 6])

In [16]:
a[:,-1]

array([3, 6, 9])

In [17]:
a[:,-1] = 0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [18]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
np.size(a,0)

4

In [19]:
np.size(a,1)

3

In [20]:
np.ndim(a)

2

## Data is Matrix.

In [21]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [22]:
np.array(np_mix_matrix[:,1], dtype = int)

array([2, 4, 6])

# 2. Special Type of Matrix

In [4]:
a = np.zeros((2,2))
a

NameError: name 'np' is not defined

In [24]:
b = np.ones((2,2))
b

array([[1., 1.],
       [1., 1.]])

In [25]:
c = np.full((2,2),8)
c

array([[8, 8],
       [8, 8]])

In [26]:
d = np.eye(2)
d

array([[1., 0.],
       [0., 1.]])

In [27]:
c*d

array([[8., 0.],
       [0., 8.]])

In [28]:
2*np.ones((2,2))

array([[2., 2.],
       [2., 2.]])

In [29]:
np.sqrt(np.full((2,2),4))

array([[2., 2.],
       [2., 2.]])

In [30]:
np.empty([5,5])

array([[4.67290496e-310, 8.15208316e-322, 9.29654051e+242,
        4.39324667e+228, 5.37988202e+228],
       [1.38795503e+219, 2.86749934e+161, 5.95144714e+228,
        1.99886516e+161, 1.09313427e+189],
       [3.31602997e-080, 2.16063140e+233, 8.48254144e+175,
        2.99688141e-080, 1.43769634e-023],
       [3.23225296e-295, 1.24571164e+137, 6.51686540e+256,
        9.98390183e+164, 3.89570063e+034],
       [7.38255668e+015, 6.46676985e+256, 5.03211681e-071,
        3.28175647e-028, 5.05060978e+223]])

# 3. Random

In [31]:
np.random.rand()

0.2961627941681809

In [32]:
np.random.randint(5)

4

In [3]:
np.seed = 1
np.random.randint(2,5)

NameError: name 'np' is not defined

In [34]:
np.random.rand(5,5)

array([[0.03013377, 0.77988736, 0.70001926, 0.93476893, 0.46319549],
       [0.00472115, 0.99820131, 0.27688426, 0.12048633, 0.94747641],
       [0.40619894, 0.47836167, 0.34420971, 0.67387839, 0.33421922],
       [0.68949797, 0.04407863, 0.66507604, 0.41412383, 0.41597101],
       [0.79863753, 0.16950698, 0.77536549, 0.47746363, 0.12864667]])

In [35]:
np.round(np.random.rand(5,5))

array([[1., 1., 1., 0., 0.],
       [0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 1., 0.]])

In [2]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,5)

NameError: name 'np' is not defined